### ISSUE TITLE
Lack of Diversity in image pool

### ISSUE THREAD

**Issue by DanRader** [maximedegreve/TinyFaces-Sketch-Plugin#13]
Is there any way we could infuse this plugin with more humans of color. I love this plugin but end up having to abandon it and mix in my own images with Craft. I'd be happy to contribute free stock portraits I've collected from the internet dot com. 

Also, see these https://lifehacker.com/where-to-find-more-diverse-stock-photos-1818506868

**Comment by maximedegreve** [comment]
Hi @DanRader 

I totally agree with you, I've tried to tweet multiple times around this to get a more diverse crowd on our site but without a lot of luck.

TinyFaces is a platform where people can upload their own face. Therefore we're highly dependant on those users when it comes to diversity.

Unfortunately we don't accept photos where the consent is not given directly by the person in the photo. 

Feel free to tweet our platform out and share it across your community as this is highly needed.

👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧

**Comment by jamesrobinson50** [comment]
Hi Maxime, could we at least remove this image from the dataset as part of this effort?

<img width="763" alt="screen shot 2019-02-06 at 4 37 12 am" src="https://user-images.githubusercontent.com/4239316/52332614-23f5fe00-29c9-11e9-8c71-80bbcb173d0f.png">

**Comment by maximedegreve** [comment]
@jamesrobinson50 Thank you for reporting this. We agree that dressing up as a racial group isn't acceptable. Especially while Native Americans continue to experience discrimination in the United States. We removed the image from our database and removed it from the comments here for the same reason.
