### ISSUE TITLE
No photos appear when using the plugin

### ISSUE THREAD

**Issue by diannealonsagay** [maximedegreve/TinyFaces-Sketch-Plugin#15]
Sketch ver 47
TinyFaces ver 2.2

Problem: No photos appear when any options are used in the plugin

**Comment by gogolubev** [comment]
Same problem. Same versions.

**Comment by mczachurski** [comment]
I've the same issue.

**Comment by chadwhitaker** [comment]
😞

**Comment by maximedegreve** [comment]
Thank you for reporting this. I was able to reproduce this with the latest version of Sketch and will try to fix this ASAP.

**Comment by maximedegreve** [comment]
The issue is no resolved in a new update of TinyFaces (2.3). 😃

**Comment by gogolubev** [comment]
Thanks @maximedegreve
