### ISSUE TITLE
Images are not replaced in symbols

### ISSUE THREAD

**Issue by MichaelWholesome** [maximedegreve/TinyFaces-Sketch-Plugin#16]
I'm running Sketch 47.1, TinyFaces 2.3, and MacOS 10.13.1.

The plugin works great for me except inside of symbols. After choosing which layer to insert picture into, nothing happens.

![a](https://thumbs.gfycat.com/RipeWhisperedEasternnewt-size_restricted.gif)

**Comment by Roywcm** [comment]
Same issue here

**Comment by maximedegreve** [comment]
👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧

Hi guys, 

Just released a new update which hopefully should resolve all those problems.
Let me know if that works.

Thanks

👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧👦🏾👴🏻👩🏻👧

**Comment by maximedegreve** [comment]
cc @Roywcm

**Comment by MichaelWholesome** [comment]
Confirmed working for me, thanks a ton!
