### ISSUE TITLE
Randomized Photos

### ISSUE THREAD

**Issue by dpapageorge** [maximedegreve/TinyFaces-Sketch-Plugin#2]
It'd be nice if there was a randomize feature that would allow users to get a new and random image from the pool of images.

**Comment by maximedegreve** [comment]
@dpapageorge I totally agree! It's on my list to do next! 😁

**Comment by KeeyaWangJones** [comment]
I would like to help and contribute to this plugin. :) I can offer diversity , gender and cultural mix to the image pool. If we can separate the pool into Female, Male, LGBTQ Friendly, Neutral, Age, etc. Maybe we can add a custom collection the user can use again that maybe have their own images.

**Comment by maximedegreve** [comment]
We could definitely do male and female, but those calls don't exist yet on the server side so you might want to check out https://github.com/maximedegreve/TinyFaces instead. However we don't have any age or LGBTQ information. We only have male or female.

**Comment by maximedegreve** [comment]
The sketch plugin receives now pictures rated in quality of 10 in a random order. Soon I will extend the plugin to return them all and being able to filter on female and male.
