### ISSUE TITLE
Nothing happens after using plug-in

### ISSUE THREAD

**Issue by avorio** [maximedegreve/TinyFaces-Sketch-Plugin#23]
![2018-12-07 12 58 40](https://user-images.githubusercontent.com/649020/49654763-e0f6c900-fa1f-11e8-8437-98c083ba2408.gif)

<img width="317" alt="screen shot 2018-12-07 at 12 59 16" src="https://user-images.githubusercontent.com/649020/49654792-f3710280-fa1f-11e8-8d51-177f72872978.png">

<img width="632" alt="screen shot 2018-12-07 at 12 59 26" src="https://user-images.githubusercontent.com/649020/49654791-f3710280-fa1f-11e8-8f2b-3d2a9e798bdd.png">

```
[3 <private> stream, pid: 2059, url: https://raw.githubusercontent.com/maximedegreve/TinyFaces-Sketch-Plugin/master/update/appcast.xml, tls] cancelled
	[3.1 175878D3-C268-4D1A-92BE-A9EFD7E8E78C <private>.53760<-><private>]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 31.091s, DNS @0.000s took 0.127s, TCP @0.127s took 0.018s, TLS took 0.054s
	bytes in/out: 5640/639, packets in/out: 6/3, rtt: 0.017s, retransmitted packets: 0, out-of-order packets: 0
```

**Comment by mikeplain** [comment]
The same issue here. Sketch v 52.5

**Comment by maximedegreve** [comment]
@mikeplain @auermi @avorio A new plugin is available here: 
https://github.com/maximedegreve/TinyFaces-Sketch-Plugin/releases/download/v0.3.0/tinyfaces.sketchplugin.zip

**Comment by mikeplain** [comment]
Thanks!! It works!
