### ISSUE TITLE
'TinyFaces can't be contacted. Check your internet...'

### ISSUE THREAD

**Issue by jonohewitt** [maximedegreve/TinyFaces-Sketch-Plugin#26]
'TinyFaces can't be contacted. Check your internet...' error pops up when selecting a 'Fill with...' option from the plugin toolbar or using a keyboard shortcut. 

Sketch DevTools console is showing:
```
NSURLError
>properties: Array[0]
>classMethods: Array[0]
>instanceMethods: Array
0: encodeWithCoder:
>protocols: Array[0]
```
Sketch Version 64 (93537), TinyFaces 0.3.0

**Comment by maximedegreve** [comment]
Our server went down. Sorry for that.

**Comment by mraaroncruz** [comment]
@maximedegreve 
It's happening again.
Same tinyfaces version, Sketch 67.2
Also the site's SSL cert is bad `NET::ERR_CERT_DATE_INVALID`
Cheers!

**Comment by maximedegreve** [comment]
Sorry for this @mraaroncruz . Give it a try again

**Comment by mraaroncruz** [comment]
@maximedegreve Yes, it works again. Thank you
