### ISSUE TITLE
plugin not working now

### ISSUE THREAD

**Issue by janily** [maximedegreve/TinyFaces-Sketch-Plugin#27]
hi, sketch plugin not working now?

![image](https://user-images.githubusercontent.com/1013557/126734187-8bee1c38-c09d-46f5-9b33-0dfd8735c369.png)

**Comment by maximedegreve** [comment]
@janily I'm having trouble releasing a new update for this plugin due to a bug in the Sketch Package Manager. I'm currently working with Sketch right now to get a new version out.

**Comment by janily** [comment]
@maximedegreve  thanks, it is working now.

**Comment by maximedegreve** [comment]
@janily 🎉
