### ISSUE TITLE
Plugin can not download - Not Found

### ISSUE THREAD

**Issue by rishabhbdev** [maximedegreve/TinyFaces-Sketch-Plugin#28]
Hi! @maximedegreve,
As mentioned in your README.md file, the link to download newly released plugin ie. https://github.com/maximedegreve/TinyFaces-Sketch-Plugin/blob/master/README.md does not sem to work - "Not Found" OR shows a "404" status code.

Perhaps, the correct link should be this -> https://github.com/maximedegreve/TinyFaces-Sketch-Plugin/releases/download/v0.6.2/tinyfaces.sketchplugin.zip
I fetched around this link in releases tab of this repo.

**Comment by maximedegreve** [comment]
Thank you for reporting @rishabhbdev. This is fixed now. 🥳
