### ISSUE TITLE
Makes Sketch crash

### ISSUE THREAD

**Issue by shanecarmody** [maximedegreve/TinyFaces-Sketch-Plugin#6]
Hey 👋🏻

- I have a rectangle drawn on my artboard. 
- I select it. 
- I click on `TinyFaces > Fill with high quality…`. 
- Sketch crashes.

I tried all the other options too and the same thing happens.

I’m using Sketch 42.

**Comment by vernerk** [comment]
Same here

**Comment by tchret** [comment]
+1

**Comment by maximedegreve** [comment]
@shanecarmody @vernerk @tchret Sorry for that! Our SSL certificate expired. This should be resolved now...

**Comment by shanecarmody** [comment]
YES! It works!

**Comment by tchret** [comment]
@maximedegreve thanks! awesome plugin 👍
