### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [maximedegreve/TinyFaces-Sketch-Plugin#7]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by beny26la** [comment]
Hi 
The TinyFaces plugin crash on sketch version 441. Is there an update to avoid this issue?
Thank you for the answer

**Comment by maximedegreve** [comment]
@beny26la I think our api was down then. Are you still experiencing this?

**Comment by maximedegreve** [comment]
@bomberstudios Will look into this, this weekend! 💃

**Comment by maximedegreve** [comment]
@bomberstudios I think I set it all up... Might be worth to double check... It's on the master branch now.

**Comment by bomberstudios** [comment]
Looks good from here, thanks for implementing that : )
